backend:
  name: git-gateway
  branch: main

media_folder: 'public/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'

locale: 'en'

collections: # A list of collections the CMS should be able to edit
  - name: 'show' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Show' # Used in the UI, ie.: "New Post"
    folder: 'src/pages/shows' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Layout" , name: "layout", widget: "hidden", default: "../../components/Show.astro" }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', date_format: "DD/MM/YYYY" }
      - { label: 'Venue', name: 'venue', widget: 'string' }
      - { label: 'City', name: 'city', widget: 'string' }
      - { label: 'Country', name: 'country', widget: 'string' }
      - label: 'Songs'
        name: 'songs'
        widget: 'list'
        summary: {{ fields.title }}
        fields:
          - label: Title
          - name: title
